# Configuration for Instant Translator Chrome Extension
# Note: This YAML file is provided as a reference. The extension uses the JSON format.

version: '1.0'

# Default language settings
defaultTargetLanguage: 'English'
defaultSourceLanguage: 'Auto-detect'  # Changed from 'auto' to 'Auto-detect' to match the name in supportedLanguages

# Active Languages (Enabled in the UI)
supportedLanguages:
  - code: 'auto'
    name: 'Auto-detect'
    enabled: true
  - code: 'en'
    name: 'English'
    enabled: true
  - code: 'ja'
    name: 'Japanese'
    enabled: true
  - code: 'es'
    name: 'Spanish'
    enabled: true

# Languages available but disabled by default
disabledLanguages:
  - code: 'fr'
    name: 'French'
  - code: 'de'
    name: 'German' 
  - code: 'it'
    name: 'Italian'
  - code: 'pt'
    name: 'Portuguese'
  - code: 'ru'
    name: 'Russian'
  - code: 'zh'
    name: 'Chinese'
  - code: 'ko'
    name: 'Korean'
  - code: 'ar'
    name: 'Arabic'
  - code: 'hi'
    name: 'Hindi'

# --- Backend Specific Settings Removed --- 
# Model definitions, language pair preferences, and detection patterns
# are now handled within the specific backend modules (e.g., backends/ollama.js)

# Select the active translation backend
activeBackend: 'ollama' # Options: 'ollama', 'chromeApi' (when implemented)

# Backend Configuration
backendSettings:
  ollama:
    # Ollama specific models, endpoints, languagePairs, etc.
    # Move the existing models, languagePairs, languageDetection here
    models:
      - id: 'gemma3:1b'
        # ... rest of gemma3:1b config
      - id: '7shi/gemma-2-jpn-translate:2b-instruct-q8_0'
        # ... rest of gemma 2 config
    languagePairs:
       # ... existing languagePairs
    languageDetection:
       # ... existing languageDetection
  chromeApi:
    # Settings specific to Chrome API (if any)
    # e.g., useHighQualityModel: true (hypothetical)
    detectOnly: false # Maybe an option to only use it for detection?

# ... (You might remove the top-level models/languagePairs/languageDetection now)
    